"resources"	
{
	"materials/ninetower/lobby/suiteslogo.vmt"	"file"
	"materials/ninetower/lobby/soonlogo.vtf"	"file"
	"materials/ninetower/lobby/suiteslogo.vtf"	"file"
	"materials/ninetower/lobby/deathmatchlogo.vtf"	"file"
	"materials/ninetower/lobby/gamemodeslogo.vtf"	"file"
	"materials/ninetower/lobby/ninetower.vtf"	"file"
	"materials/billie/dev_measuregeneric02e.vmt"	"file"
	"materials/ninetower/lobby/melonracelogo.vmt"	"file"
	"materials/billie/dev_measuregeneric02c.vtf"	"file"
	"materials/ninetower/lobby/soonlogo.vmt"	"file"
	"materials/billie/dev_measuregeneric02c.vmt"	"file"
	"materials/billie/dev_measuregeneric02.vmt"	"file"
	"materials/billie/dev_measuregeneric02f.vtf"	"file"
	"materials/billie/dev_measuregeneric02d.vtf"	"file"
	"materials/billie/dev_measuregeneric02.vtf"	"file"
	"materials/billie/dev_measuregeneric02b.vmt"	"file"
	"materials/ninetower/lobby/lobbylogo.vmt"	"file"
	"materials/billie/dev_measuregeneric02f.vmt"	"file"
	"materials/ninetower/lobby/deathmatchlogo.vmt"	"file"
	"materials/billie/dev_measuregeneric02b.vtf"	"file"
	"materials/ninetower/lobby/melonracelogo.vtf"	"file"
	"materials/ninetower/lobby/ninetower.vmt"	"file"
	"materials/billie/dev_measuregeneric02e.vtf"	"file"
	"materials/ninetower/lobby/lobbylogo.vtf"	"file"
	"materials/billie/dev_measuregeneric02d.vmt"	"file"
	"materials/ninetower/lobby/gamemodeslogo.vmt"	"file"
	"materials/ninetower/lobby/ninetenthslogo.vtf"	"file"
	"materials/ninetower/lobby/ninetenthslogo.vmt"	"file"
	"materials/ninetower/ninetenth/evilninetower.vmt" "file"
	"materials/ninetower/ninetenth/evilninetower.vtf" "file"
}
